server:
  port: ${PORT:8300}
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:pabi-eureka}:${EUREKA_SERVER_PORT:8000}/eureka

spring:
  application:
    name: item-service